services:
  lgu-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lgu-chat-app
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVER_HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET:-}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - DOMAIN_NAME=${DOMAIN_NAME:-lgu-chat.lguquezon.local}
      - CUSTOM_ALLOWED_IPS=${CUSTOM_ALLOWED_IPS:-}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL:-http://lgu-chat.lguquezon.local}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://lgu-chat.lguquezon.local}
    volumes:
      # Persist database data
      - ./data:/app/data
      # Persist uploaded files
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/auth/me"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - lgu-chat-network

networks:
  lgu-chat-network:
    driver: bridge

# Optional: use named volumes instead of bind mounts
# volumes:
#   lgu-chat-data:
#   lgu-chat-uploads: 