services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    restart: unless-stopped
